server:
  port: 8888
  servlet:
    context-path: /order-service

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
